[theme]
base = "dark"
primaryColor = "#26d0a8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
